give @s sq:adamantite_block 64
give @s sq:aluminum_block 64
give @s sq:black_steel_block 64
give @s sq:bronze_block 64
give @s sq:cobalt_block 64
give @s sq:electrum_block 64
give @s sq:lead_block 64
give @s sq:mythril_block 64
give @s sq:nickel_block 64
give @s sq:platinum_block 64
give @s sq:silver_block 64
give @s sq:steel_block 64
give @s sq:tin_block 64
give @s sq:titanium_block 64
give @s sq:tungsten_block 64
give @s sq:uranium_block 64
give @s sq:zinc_block 64
give @s sq:brass_block 64