#bridge-file-version: #3
give @s sq:adamantite_ingot 64
give @s sq:aluminum_ingot 64
give @s sq:black_steel_ingot 64
give @s sq:bronze_ingot 64
give @s sq:cobalt_ingot 64
give @s sq:electrum_ingot 64
give @s sq:lead_ingot 64
give @s sq:mithril_ingot 64
give @s sq:nickel_ingot 64
give @s sq:platinum_ingot 64
give @s sq:silver_ingot 64
give @s sq:steel_ingot 64
give @s sq:tin_ingot 64
give @s sq:titanium_ingot 64
give @s sq:tungsten_ingot 64
give @s sq:uranium_ingot 64
give @s sq:zinc_ingot 64
give @s sq:brass_ingot 64