give @s sq:adamantite_ore 64
give @s sq:aluminum_ore 64
give @s sq:cobalt_ore 64
give @s sq:electrum_ore 64
give @s sq:lead_ore 64
give @s sq:mythril_ore 64
give @s sq:nickel_ore 64
give @s sq:platinum_ore 64
give @s sq:silver_ore 64
give @s sq:tin_ore 64
give @s sq:titanium_ore 64
give @s sq:tungsten_ore 64
give @s sq:uranium_ore 64
give @s sq:zinc_ore 64